# Generated by Django 5.2.14 on 2026-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria_scores', models.JSONField(default=list)),
                ('total_score', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
    ]
