# Generated by Django 5.2.14 on 2026-05-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judging', '0001_initial'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submissions.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionscore',
            unique_together={('submission', 'judge')},
        ),
    ]
