# Generated by Django 5.2.14 on 2026-05-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonjudge',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='hackathons.hackathon'),
        ),
        migrations.AddField(
            model_name='hackathonjudge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonparticipant',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hackathons.hackathon'),
        ),
        migrations.AddField(
            model_name='hackathonparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonjudge',
            unique_together={('hackathon', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='hackathonparticipant',
            unique_together={('hackathon', 'user')},
        ),
    ]
