# Generated by Django 5.2.14 on 2026-05-17 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
