# Generated by Django 5.2.14 on 2026-05-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='hackathons.hackathon'),
        ),
    ]
