# Generated by Django 5.2.14 on 2026-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_url', models.URLField()),
                ('demo_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('disqualified', 'Disqualified')], default='draft', max_length=24)),
                ('final_score', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_evaluation', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
